// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AcademiaBackEnd.Data.Models;

[Table("relacionamentos")]
[Index("AlunoId", Name = "IX_relacionamentos", IsUnique = true)]
public partial class Relacionamento
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("aluno_id")]
    public long AlunoId { get; set; }

    [Column("professor_id")]
    public long ProfessorId { get; set; }

    [Column("data_confirmacao", TypeName = "datetime")]
    public DateTime? DataConfirmacao { get; set; }

    [ForeignKey("AlunoId")]
    [InverseProperty("RelacionamentoAluno")]
    public virtual Usuario Aluno { get; set; }

    [ForeignKey("ProfessorId")]
    [InverseProperty("RelacionamentoProfessors")]
    public virtual Usuario Professor { get; set; }
}