// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AcademiaBackEnd.Data.Models;

[Table("sessao_treino")]
public partial class SessaoTreino
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("hora_inicio", TypeName = "datetime")]
    public DateTime HoraInicio { get; set; }

    [Column("hora_fim", TypeName = "datetime")]
    public DateTime? HoraFim { get; set; }

    [Column("cliente_id")]
    public long ClienteId { get; set; }

    [Column("treino_id")]
    public long TreinoId { get; set; }

    [Required]
    [Column("status_treino")]
    [StringLength(255)]
    [Unicode(false)]
    public string StatusTreino { get; set; }

    [ForeignKey("ClienteId")]
    [InverseProperty("SessaoTreinos")]
    public virtual Usuario Cliente { get; set; }

    [ForeignKey("TreinoId")]
    [InverseProperty("SessaoTreinos")]
    public virtual Treino Treino { get; set; }
}