// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AcademiaBackEnd.Data.Models;

[Table("usuario")]
public partial class Usuario
{
    [Key]
    public long Id { get; set; }

    [Required]
    [Column("nome")]
    [StringLength(80)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Required]
    [Column("email")]
    [StringLength(255)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [Column("senha")]
    [StringLength(255)]
    [Unicode(false)]
    public string Senha { get; set; }

    [Column("data_nascimento")]
    public DateOnly DataNascimento { get; set; }

    [Column("peso")]
    public double? Peso { get; set; }

    [Column("altura")]
    public double? Altura { get; set; }

    [Required]
    [Column("role")]
    [StringLength(50)]
    [Unicode(false)]
    public string Role { get; set; }

    [Required]
    [Column("img")]
    [StringLength(255)]
    [Unicode(false)]
    public string Img { get; set; }

    [InverseProperty("Aluno")]
    public virtual Relacionamento RelacionamentoAluno { get; set; }

    [InverseProperty("Professor")]
    public virtual ICollection<Relacionamento> RelacionamentoProfessors { get; set; } = new List<Relacionamento>();

    [InverseProperty("Cliente")]
    public virtual ICollection<SessaoTreino> SessaoTreinos { get; set; } = new List<SessaoTreino>();

    [InverseProperty("Cliente")]
    public virtual ICollection<Solicitaco> SolicitacoClientes { get; set; } = new List<Solicitaco>();

    [InverseProperty("Professor")]
    public virtual ICollection<Solicitaco> SolicitacoProfessors { get; set; } = new List<Solicitaco>();

    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<Treino> Treinos { get; set; } = new List<Treino>();
}